### ISSUE TITLE
Don't work with gulp 3.8

### ISSUE THREAD

**Issue by ZoRDoK** [teltploek/gulp-jade-find-affected#2]
TypeError: Object #<Object> has no method 'indexOf'
    at /home/slava/dev/wally/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:25:17

**Comment by teltploek** [comment]
I'm sorry, but I'm unable to reproduce. If the problem continues, please open new issue with steps to reproduce. Thanks!
