### ISSUE TITLE
Triggering for extends

### ISSUE THREAD

**Issue by chrisjansky** [teltploek/gulp-jade-find-affected#3]
Works great with includes, but extends (used as basic page templates) don't do nothing for me. Any chance to add that functionality? Thanks!

http://jade-lang.com/reference/extends/

**Comment by piotrd** [comment]
This plugin may be hat you need, @chrisjansky: https://github.com/juanfran/gulp-jade-inheritance

**Comment by nkCoding** [comment]
I hope this plugin will support 'extends' as @chrisjansky suggested.
Changes of templates / layouts DO affect pages that inherit from them.

I also see the plugin @piotrd mentioned above, but is there any way to use both plugins to get pages rebuild either related templates or included files change?

**Comment by piotrd** [comment]
@nkCoding: I'd guess there's no point in running two at a time, if one (gulp-jade-inheritance) claims to cover both cases.

**Comment by teltploek** [comment]
I agree. I will do this as soon as I can find the time for it - I think I can get this done in a weeks time or something like that.

**Comment by ZombieHippie** [comment]
I recommend looking at [how jade-inheritance uses the jade parser to determine dependents](https://github.com/paulyoung/jade-inheritance/blob/05e78fcf522b56115805a3b79083bf54db189c22/src/parser.coffee#L49-76).

**Comment by colelawrence** [comment]
Thanks @teltploek! Good job :-)

**Comment by teltploek** [comment]
No problem, and thanks. I'm sorry it took so long :-) !
